\documentclass[10pt,xcolor=x11names,compress]{beamer}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{booktabs}
\usepackage[round]{natbib}
\renewcommand{\newblock}{} % Get natbib and beamer working together: http://tex.stackexchange.com/questions/1969/beamer-and-natbib

%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{lclGWAS}


\newcommand{\R}{\texttt{R}}
\newcommand{\pkgname}{\texttt{lclGWAS}}
\newcommand{\Rcpp}{\texttt{Rcpp}}

\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]

\setbeamertemplate{enumerate item}{\insertenumlabel}
\setbeamertemplate{enumerate subitem}{\alph{enumii}.}


\begin{document}
<<setup1, include=FALSE, echo=FALSE>>=
require(knitr)
@

<<setup2, include=FALSE,echo=FALSE>>=
options(width=80)  # make the printing fit on the page
set.seed(1121)     # make the results repeatable
stdt<-date()
@

\begin{frame}
	\title{\pkgname}
	\subtitle{Efficient Estimation of Discrete-Time Multivariate Frailty Model Using Exact Likelihood Function for Grouped Survival Data}
	\date{2016-11-10}
	\titlepage
\end{frame}


\begin{frame}{Introduction}
  \begin{itemize}
    \item This document provides an example for using the \pkgname{} package to calculate the baseline hazard, effect parameter, and frailty variance for a discrete-time frailty model containing mixed effects by exact likelihood function.
    \item The major algorithm in this package is written in C++, which is ported to \R{} by \Rcpp{}, to facilitate fast computation. 
  \end{itemize}
\end{frame}

\begin{frame}[fragile]{betaEst}
<<function mutiple threads, eval=FALSE>>=
 beta <- betaEst(fam_size, alpha, dtime, 
                 delta, g, var, m, lower = 0, upper = 2)
@
Function aguments:
\begin{description}
	\item[\texttt{fam\_size}:] A vector contains the number of sample for each family.
 	\item[\texttt{alpha}:] Baseline hazard vector for each time intervals.
 	\item[\texttt{dtime}:] A vector of observed survival time for each sample.
	\item[\texttt{delta}:] A event indicator vector: 1 means event and 0 means otherwise.
	\item[\texttt{g}:] A vector for numerical gene type of each sample.
	\item[\texttt{var}:] A scalar for frailty variance.
    \item[\texttt{m}:] A integer for the number of families.
	\item[\texttt{lower}:] A scalar for the lower bound for the effect parameter estimation.
	\item[\texttt{upper}:] A scalar for the upper bound for the effect parameter estimation.
\end{description}
\end{frame}

\begin{frame}[fragile]{Returned Value of \texttt{betaEst} }
Function returns:
\begin{description}
 	\item[\texttt{betaEst}:] A scalar for the estimated effect size.
\end{description}
\end{frame}


\begin{frame}[fragile]{varEst}
<<function mutiple threads var, eval=FALSE>>=
 var <- varEst(fam_size, alpha, dtime, 
               delta, g, beta, m, lower = 0, upper = 2)
@
Function aguments:
\begin{description}
	\item[\texttt{fam\_size}:] A vector contains the number of sample for each family.
 	\item[\texttt{alpha}:] Baseline hazard vector for each time intervals.
 	\item[\texttt{dtime}:] A vector of observed survival time for each sample.
	\item[\texttt{delta}:] A event indicator vector: 1 means event and 0 means otherwise.
	\item[\texttt{g}:] A vector for numerical gene type of each sample.
	\item[\texttt{beta}:] A scalar for effect parameter.
    \item[\texttt{m}:] A integer for the number of families.
	\item[\texttt{lower}:] A scalar for the lower bound for the effect parameter estimation.
	\item[\texttt{upper}:] A scalar for the upper bound for the effect parameter estimation.
\end{description}
\end{frame}

\begin{frame}[fragile]{Returned Value of \texttt{varEst}}
Function returns:
\begin{description}
 	\item[\texttt{varEst}:] A scalar for the estimated frailty variance.
\end{description}
\end{frame}

\begin{frame}[fragile]{alphaEst}
<<function mutiple threads alpha, eval=FALSE>>=
alpha <- alphaEst(fam_size, alpha, dtime, 
                  delta, g, beta, m, lower = 0, upper = 2)
@
Function aguments:
\begin{description}
	\item[\texttt{m}:] A integer to indicate which discrete-time baseline hazard.
	\item[\texttt{dtime}:] A vector of observed survival time for each sample.
	\item[\texttt{delta}:] A event indicator vector: 1 means event and 0 means otherwise.
	\item[\texttt{g}:] A vector for numerical gene type of each sample.
\end{description}
Function returns:
\begin{description}
    \item[\texttt{alphaEst}:] A scalar for the estimated baseline hazard.
\end{description}
\end{frame}

\begin{frame}[fragile]{Example}
Sample data and parameters:
<<inputPara,size='tiny'>>=
fsize  <- rep(3,3)
alphas <- c(0.7500000, 0.6666667, 0.5000000, 0.0000000)
dtimes <- c(1, 3, 3, 2, 1, 1, 2, 3, 1)
deltas <- c(1, 0, 1, 1, 1, 0, 1, 0, 1)
gs     <- c(0, 1, 1, 1, 2, 2, 0, 0, 0)
var    <- 0.2
m      <- 3
beta   <- 1
@ 
\end{frame}


\begin{frame}[fragile]{Load Package}
Load \pkgname{} (after installing its dependent packages):
<<loadpkg>>=
library(lclGWAS)
@ 
\end{frame}

\begin{frame}[fragile]{Example Execution}
Example execution
<<exp3,size='tiny'>>=
res   <- betaEst(fsize, alphas, dtimes, 
                 deltas, gs, var, m, lower = 0, upper = 2)
res
@
<<exp5,size='tiny'>>=
res   <- varEst(fsize, alphas, dtimes, 
                deltas, gs, var, beta, lower = 0, upper = 2)
res
@
<<exp6,size='tiny'>>=
res   <- alphaEst(1, dtimes, deltas, gs)
res
@
\end{frame}

\section{Session Information}
\begin{frame}[fragile]{Session Information}
<<sessinfo, echo=FALSE, include=TRUE, results='asis'>>=
toLatex(sessionInfo(), locale=FALSE)
@ 
<<times, echo=FALSE, include=TRUE>>=
print(paste("Start Time",stdt))
print(paste("End Time  ",date()))
@ 
\end{frame}

\end{document}
