# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaEst <- function(m, dtime, delta, g) {
    .Call('lclGWAS_alphaEst', PACKAGE = 'lclGWAS', m, dtime, delta, g)
}

betaEst <- function(fam_size, alpha, dtime, delta, g, var, m, lower, upper) {
    .Call('lclGWAS_betaEst', PACKAGE = 'lclGWAS', fam_size, alpha, dtime, delta, g, var, m, lower, upper)
}

varEst <- function(fam_size, alpha, dtime, delta, g, beta, m, lower, upper) {
    .Call('lclGWAS_varEst', PACKAGE = 'lclGWAS', fam_size, alpha, dtime, delta, g, beta, m, lower, upper)
}

