# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaEst <- function(dtime, delta) {
    .Call('lclGWAS_alphaEst', PACKAGE = 'lclGWAS', dtime, delta)
}

betaEst <- function(fam_group, alpha, dtime, delta, g, var, lower, upper) {
    .Call('lclGWAS_betaEst', PACKAGE = 'lclGWAS', fam_group, alpha, dtime, delta, g, var, lower, upper)
}

varEst <- function(fam_group, alpha, dtime, delta, g, beta, lower, upper) {
    .Call('lclGWAS_varEst', PACKAGE = 'lclGWAS', fam_group, alpha, dtime, delta, g, beta, lower, upper)
}

